version: "3"
services:
  # client:
  #   build:
  #     context: ./client
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - server
  #   volumes:
  #     - ./client:/app/
  #     - /app/node_modules
  server:
    build:
      context: ./server
    ports:
      - "5001:5000"
      # - "9229:9229"
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
  db:
    build:
      context: ./db
    volumes:
      - tradie-scheduling-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  tradie-scheduling-volume:
